version: "3.4"

services:
  db:
    container_name: mysql_cont
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=notes_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - cont-ntw
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    container_name: nginx_cont
    build:
      context: ./nginx/
    image: ngins-rp
    ports:
      - 80:80
    depends_on: 
      - django
    networks:
      - cont-ntw
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  django:
    container_name: django_cont 
    build:
      context: .
    image: django-app
    depends_on:
      - db
    ports: 
      - 8000:8000
    env_file:
      - ".env"
    networks:
      - cont-ntw
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  cont-ntw:

volumes:
  mysql-data:
